import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#005bc0",
        error: "#ffb4ab",
        "on-primary": "#002e68",
        "on-tertiary-fixed": "#002108",
        tertiary: "#3ce36a",
        "surface-tint": "#adc7ff",
        "on-primary-container": "#ffffff",
        "on-tertiary": "#003912",
        "on-tertiary-container": "#00320f",
        "surface-variant": "#32353c",
        background: "#10131a",
        "secondary-fixed-dim": "#ffb5a0",
        "secondary-fixed": "#ffdbd1",
        "tertiary-container": "#00a744",
        "inverse-on-surface": "#2d3038",
        outline: "#8b909f",
        "on-background": "#e0e2ec",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed": "#69ff87",
        "primary-fixed-dim": "#adc7ff",
        "on-secondary-container": "#fffbff",
        "primary-container": "#1a73e8",
        "on-secondary": "#5f1500",
        primary: "#adc7ff",
        "error-container": "#93000a",
        "surface-container-highest": "#32353c",
        "tertiary-fixed-dim": "#3ce36a",
        "surface-container": "#1d2027",
        "on-surface-variant": "#c1c6d6",
        "inverse-surface": "#e0e2ec",
        "on-surface": "#e0e2ec",
        "on-secondary-fixed": "#3b0900",
        "secondary-container": "#d73b00",
        "on-tertiary-fixed-variant": "#00531e",
        "surface-container-low": "#191c23",
        "outline-variant": "#414754",
        surface: "#10131a",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        "surface-bright": "#363941",
        "surface-container-lowest": "#0b0e15",
        "on-error": "#690005",
        "surface-container-high": "#272a31",
        secondary: "#ffb5a0",
        "surface-dim": "#10131a",
        "on-secondary-fixed-variant": "#862200",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        gutter: "20px",
        xl: "40px",
        base: "4px",
        sm: "8px",
        lg: "24px",
        "container-max": "1440px",
        xs: "4px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "stats-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "stats-xl": [
          "40px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
